// import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script';
import localFont from 'next/font/local'



const myFont = localFont({
  src: '../../public/fonts/f965fdf4.woff2',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js" async/>
        <link rel="shortcut icon" href="https://assets.ctfassets.net/fzn2n1nzq965/01hMKr6nEEGVfOuhsaMIXQ/c424849423b5f036a8892afa09ac38c7/favicon.ico" />
        <link rel="apple-touch-icon" href="https://images.ctfassets.net/fzn2n1nzq965/2EOOpI2mMZgHYBlbO44zWV/5a6c5d37402652c80567ec942c733a43/favicon.png?w=180&amp;h=180" />
        <link rel="icon" href="https://images.ctfassets.net/fzn2n1nzq965/2EOOpI2mMZgHYBlbO44zWV/5a6c5d37402652c80567ec942c733a43/favicon.png?w=180&amp;h=180" />
        <meta name="description" content="Stripe powers online and in-person payment processing and financial solutions for businesses of all sizes. Accept payments, send payouts, and automate financial processes with a suite of APIs and no-code tools." />
        <link rel="canonical" href="https://stripe.com/" />
        <link rel="alternate" href="https://stripe.com/" hrefLang="x-default" />
        <link rel="alternate" href="https://stripe.com/de-au" hrefLang="de-AU" />
        <link rel="alternate" href="https://stripe.com/au" hrefLang="en-AU" />
        <link rel="alternate" href="https://stripe.com/es-419-au" hrefLang="es-AU" />
        <link rel="alternate" href="https://stripe.com/fr-au" hrefLang="fr-AU" />
        <link rel="alternate" href="https://stripe.com/id-au" hrefLang="id-AU" />
        <link rel="alternate" href="https://stripe.com/it-au" hrefLang="it-AU" />
        <link rel="alternate" href="https://stripe.com/ja-au" hrefLang="ja-AU" />
        <link rel="alternate" href="https://stripe.com/nl-au" hrefLang="nl-AU" />
        <link rel="alternate" href="https://stripe.com/sv-au" hrefLang="sv-AU" />
        <link rel="alternate" href="https://stripe.com/th-au" hrefLang="th-AU" />
        <link rel="alternate" href="https://stripe.com/pt-br-au" hrefLang="pt-AU" />
        <link rel="alternate" href="https://stripe.com/zh-cn-au" hrefLang="zh-AU" />
        <link rel="alternate" href="https://stripe.com/at" hrefLang="de-AT" />
        <link rel="alternate" href="https://stripe.com/en-gb-at" hrefLang="en-AT" />
        <link rel="alternate" href="https://stripe.com/es-419-at" hrefLang="es-AT" />
        <link rel="alternate" href="https://stripe.com/fr-at" hrefLang="fr-AT" />
        <link rel="alternate" href="https://stripe.com/id-at" hrefLang="id-AT" />
        <link rel="alternate" href="https://stripe.com/it-at" hrefLang="it-AT" />
        <link rel="alternate" href="https://stripe.com/ja-at" hrefLang="ja-AT" />
        <link rel="alternate" href="https://stripe.com/nl-at" hrefLang="nl-AT" />
        <link rel="alternate" href="https://stripe.com/sv-at" hrefLang="sv-AT" />
        <link rel="alternate" href="https://stripe.com/th-at" hrefLang="th-AT" />
        <link rel="alternate" href="https://stripe.com/pt-br-at" hrefLang="pt-AT" />
        <link rel="alternate" href="https://stripe.com/zh-cn-at" hrefLang="zh-AT" />
        <link rel="alternate" href="https://stripe.com/de-be" hrefLang="de-BE" />
        <link rel="alternate" href="https://stripe.com/en-gb-be" hrefLang="en-BE" />
        <link rel="alternate" href="https://stripe.com/es-419-be" hrefLang="es-BE" />
        <link rel="alternate" href="https://stripe.com/fr-be" hrefLang="fr-BE" />
        <link rel="alternate" href="https://stripe.com/id-be" hrefLang="id-BE" />
        <link rel="alternate" href="https://stripe.com/it-be" hrefLang="it-BE" />
        <link rel="alternate" href="https://stripe.com/ja-be" hrefLang="ja-BE" />
        <link rel="alternate" href="https://stripe.com/nl-be" hrefLang="nl-BE" />
        <link rel="alternate" href="https://stripe.com/sv-be" hrefLang="sv-BE" />
        <link rel="alternate" href="https://stripe.com/th-be" hrefLang="th-BE" />
        <link rel="alternate" href="https://stripe.com/pt-br-be" hrefLang="pt-BE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-be" hrefLang="zh-BE" />
        <link rel="alternate" href="https://stripe.com/de-br" hrefLang="de-BR" />
        <link rel="alternate" href="https://stripe.com/en-br" hrefLang="en-BR" />
        <link rel="alternate" href="https://stripe.com/es-419-br" hrefLang="es-BR" />
        <link rel="alternate" href="https://stripe.com/fr-br" hrefLang="fr-BR" />
        <link rel="alternate" href="https://stripe.com/id-br" hrefLang="id-BR" />
        <link rel="alternate" href="https://stripe.com/it-br" hrefLang="it-BR" />
        <link rel="alternate" href="https://stripe.com/ja-br" hrefLang="ja-BR" />
        <link rel="alternate" href="https://stripe.com/nl-br" hrefLang="nl-BR" />
        <link rel="alternate" href="https://stripe.com/sv-br" hrefLang="sv-BR" />
        <link rel="alternate" href="https://stripe.com/th-br" hrefLang="th-BR" />
        <link rel="alternate" href="https://stripe.com/br" hrefLang="pt-BR" />
        <link rel="alternate" href="https://stripe.com/zh-cn-br" hrefLang="zh-BR" />
        <link rel="alternate" href="https://stripe.com/de-bg" hrefLang="de-BG" />
        <link rel="alternate" href="https://stripe.com/en-gb-bg" hrefLang="en-BG" />
        <link rel="alternate" href="https://stripe.com/es-419-bg" hrefLang="es-BG" />
        <link rel="alternate" href="https://stripe.com/fr-bg" hrefLang="fr-BG" />
        <link rel="alternate" href="https://stripe.com/id-bg" hrefLang="id-BG" />
        <link rel="alternate" href="https://stripe.com/it-bg" hrefLang="it-BG" />
        <link rel="alternate" href="https://stripe.com/ja-bg" hrefLang="ja-BG" />
        <link rel="alternate" href="https://stripe.com/nl-bg" hrefLang="nl-BG" />
        <link rel="alternate" href="https://stripe.com/sv-bg" hrefLang="sv-BG" />
        <link rel="alternate" href="https://stripe.com/th-bg" hrefLang="th-BG" />
        <link rel="alternate" href="https://stripe.com/pt-br-bg" hrefLang="pt-BG" />
        <link rel="alternate" href="https://stripe.com/zh-cn-bg" hrefLang="zh-BG" />
        <link rel="alternate" href="https://stripe.com/de-ca" hrefLang="de-CA" />
        <link rel="alternate" href="https://stripe.com/en-gb-ca" hrefLang="en-CA" />
        <link rel="alternate" href="https://stripe.com/es-419-ca" hrefLang="es-CA" />
        <link rel="alternate" href="https://stripe.com/fr-ca-ca" hrefLang="fr-CA" />
        <link rel="alternate" href="https://stripe.com/id-ca" hrefLang="id-CA" />
        <link rel="alternate" href="https://stripe.com/it-ca" hrefLang="it-CA" />
        <link rel="alternate" href="https://stripe.com/ja-ca" hrefLang="ja-CA" />
        <link rel="alternate" href="https://stripe.com/nl-ca" hrefLang="nl-CA" />
        <link rel="alternate" href="https://stripe.com/sv-ca" hrefLang="sv-CA" />
        <link rel="alternate" href="https://stripe.com/th-ca" hrefLang="th-CA" />
        <link rel="alternate" href="https://stripe.com/pt-br-ca" hrefLang="pt-CA" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ca" hrefLang="zh-CA" />
        <link rel="alternate" href="https://stripe.com/de-hr" hrefLang="de-HR" />
        <link rel="alternate" href="https://stripe.com/en-gb-hr" hrefLang="en-HR" />
        <link rel="alternate" href="https://stripe.com/es-419-hr" hrefLang="es-HR" />
        <link rel="alternate" href="https://stripe.com/fr-hr" hrefLang="fr-HR" />
        <link rel="alternate" href="https://stripe.com/id-hr" hrefLang="id-HR" />
        <link rel="alternate" href="https://stripe.com/it-hr" hrefLang="it-HR" />
        <link rel="alternate" href="https://stripe.com/ja-hr" hrefLang="ja-HR" />
        <link rel="alternate" href="https://stripe.com/nl-hr" hrefLang="nl-HR" />
        <link rel="alternate" href="https://stripe.com/sv-hr" hrefLang="sv-HR" />
        <link rel="alternate" href="https://stripe.com/th-hr" hrefLang="th-HR" />
        <link rel="alternate" href="https://stripe.com/pt-br-hr" hrefLang="pt-HR" />
        <link rel="alternate" href="https://stripe.com/zh-cn-hr" hrefLang="zh-HR" />
        <link rel="alternate" href="https://stripe.com/de-cy" hrefLang="de-CY" />
        <link rel="alternate" href="https://stripe.com/en-gb-cy" hrefLang="en-CY" />
        <link rel="alternate" href="https://stripe.com/es-419-cy" hrefLang="es-CY" />
        <link rel="alternate" href="https://stripe.com/fr-cy" hrefLang="fr-CY" />
        <link rel="alternate" href="https://stripe.com/id-cy" hrefLang="id-CY" />
        <link rel="alternate" href="https://stripe.com/it-cy" hrefLang="it-CY" />
        <link rel="alternate" href="https://stripe.com/ja-cy" hrefLang="ja-CY" />
        <link rel="alternate" href="https://stripe.com/nl-cy" hrefLang="nl-CY" />
        <link rel="alternate" href="https://stripe.com/sv-cy" hrefLang="sv-CY" />
        <link rel="alternate" href="https://stripe.com/th-cy" hrefLang="th-CY" />
        <link rel="alternate" href="https://stripe.com/pt-br-cy" hrefLang="pt-CY" />
        <link rel="alternate" href="https://stripe.com/zh-cn-cy" hrefLang="zh-CY" />
        <link rel="alternate" href="https://stripe.com/de-cz" hrefLang="de-CZ" />
        <link rel="alternate" href="https://stripe.com/en-gb-cz" hrefLang="en-CZ" />
        <link rel="alternate" href="https://stripe.com/es-419-cz" hrefLang="es-CZ" />
        <link rel="alternate" href="https://stripe.com/fr-cz" hrefLang="fr-CZ" />
        <link rel="alternate" href="https://stripe.com/id-cz" hrefLang="id-CZ" />
        <link rel="alternate" href="https://stripe.com/it-cz" hrefLang="it-CZ" />
        <link rel="alternate" href="https://stripe.com/ja-cz" hrefLang="ja-CZ" />
        <link rel="alternate" href="https://stripe.com/nl-cz" hrefLang="nl-CZ" />
        <link rel="alternate" href="https://stripe.com/sv-cz" hrefLang="sv-CZ" />
        <link rel="alternate" href="https://stripe.com/th-cz" hrefLang="th-CZ" />
        <link rel="alternate" href="https://stripe.com/pt-br-cz" hrefLang="pt-CZ" />
        <link rel="alternate" href="https://stripe.com/zh-cn-cz" hrefLang="zh-CZ" />
        <link rel="alternate" href="https://stripe.com/de-dk" hrefLang="de-DK" />
        <link rel="alternate" href="https://stripe.com/en-gb-dk" hrefLang="en-DK" />
        <link rel="alternate" href="https://stripe.com/es-419-dk" hrefLang="es-DK" />
        <link rel="alternate" href="https://stripe.com/fr-dk" hrefLang="fr-DK" />
        <link rel="alternate" href="https://stripe.com/id-dk" hrefLang="id-DK" />
        <link rel="alternate" href="https://stripe.com/it-dk" hrefLang="it-DK" />
        <link rel="alternate" href="https://stripe.com/ja-dk" hrefLang="ja-DK" />
        <link rel="alternate" href="https://stripe.com/nl-dk" hrefLang="nl-DK" />
        <link rel="alternate" href="https://stripe.com/sv-dk" hrefLang="sv-DK" />
        <link rel="alternate" href="https://stripe.com/th-dk" hrefLang="th-DK" />
        <link rel="alternate" href="https://stripe.com/pt-br-dk" hrefLang="pt-DK" />
        <link rel="alternate" href="https://stripe.com/zh-cn-dk" hrefLang="zh-DK" />
        <link rel="alternate" href="https://stripe.com/de-ee" hrefLang="de-EE" />
        <link rel="alternate" href="https://stripe.com/en-gb-ee" hrefLang="en-EE" />
        <link rel="alternate" href="https://stripe.com/es-419-ee" hrefLang="es-EE" />
        <link rel="alternate" href="https://stripe.com/fr-ee" hrefLang="fr-EE" />
        <link rel="alternate" href="https://stripe.com/id-ee" hrefLang="id-EE" />
        <link rel="alternate" href="https://stripe.com/it-ee" hrefLang="it-EE" />
        <link rel="alternate" href="https://stripe.com/ja-ee" hrefLang="ja-EE" />
        <link rel="alternate" href="https://stripe.com/nl-ee" hrefLang="nl-EE" />
        <link rel="alternate" href="https://stripe.com/sv-ee" hrefLang="sv-EE" />
        <link rel="alternate" href="https://stripe.com/th-ee" hrefLang="th-EE" />
        <link rel="alternate" href="https://stripe.com/pt-br-ee" hrefLang="pt-EE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ee" hrefLang="zh-EE" />
        <link rel="alternate" href="https://stripe.com/de-fi" hrefLang="de-FI" />
        <link rel="alternate" href="https://stripe.com/en-gb-fi" hrefLang="en-FI" />
        <link rel="alternate" href="https://stripe.com/es-419-fi" hrefLang="es-FI" />
        <link rel="alternate" href="https://stripe.com/fr-fi" hrefLang="fr-FI" />
        <link rel="alternate" href="https://stripe.com/id-fi" hrefLang="id-FI" />
        <link rel="alternate" href="https://stripe.com/it-fi" hrefLang="it-FI" />
        <link rel="alternate" href="https://stripe.com/ja-fi" hrefLang="ja-FI" />
        <link rel="alternate" href="https://stripe.com/nl-fi" hrefLang="nl-FI" />
        <link rel="alternate" href="https://stripe.com/sv-fi" hrefLang="sv-FI" />
        <link rel="alternate" href="https://stripe.com/th-fi" hrefLang="th-FI" />
        <link rel="alternate" href="https://stripe.com/pt-br-fi" hrefLang="pt-FI" />
        <link rel="alternate" href="https://stripe.com/zh-cn-fi" hrefLang="zh-FI" />
        <link rel="alternate" href="https://stripe.com/de-fr" hrefLang="de-FR" />
        <link rel="alternate" href="https://stripe.com/en-gb-fr" hrefLang="en-FR" />
        <link rel="alternate" href="https://stripe.com/es-419-fr" hrefLang="es-FR" />
        <link rel="alternate" href="https://stripe.com/fr" hrefLang="fr-FR" />
        <link rel="alternate" href="https://stripe.com/id-fr" hrefLang="id-FR" />
        <link rel="alternate" href="https://stripe.com/it-fr" hrefLang="it-FR" />
        <link rel="alternate" href="https://stripe.com/ja-fr" hrefLang="ja-FR" />
        <link rel="alternate" href="https://stripe.com/nl-fr" hrefLang="nl-FR" />
        <link rel="alternate" href="https://stripe.com/sv-fr" hrefLang="sv-FR" />
        <link rel="alternate" href="https://stripe.com/th-fr" hrefLang="th-FR" />
        <link rel="alternate" href="https://stripe.com/pt-br-fr" hrefLang="pt-FR" />
        <link rel="alternate" href="https://stripe.com/zh-cn-fr" hrefLang="zh-FR" />
        <link rel="alternate" href="https://stripe.com/de" hrefLang="de-DE" />
        <link rel="alternate" href="https://stripe.com/en-gb-de" hrefLang="en-DE" />
        <link rel="alternate" href="https://stripe.com/es-419-de" hrefLang="es-DE" />
        <link rel="alternate" href="https://stripe.com/fr-de" hrefLang="fr-DE" />
        <link rel="alternate" href="https://stripe.com/id-de" hrefLang="id-DE" />
        <link rel="alternate" href="https://stripe.com/it-de" hrefLang="it-DE" />
        <link rel="alternate" href="https://stripe.com/ja-de" hrefLang="ja-DE" />
        <link rel="alternate" href="https://stripe.com/nl-de" hrefLang="nl-DE" />
        <link rel="alternate" href="https://stripe.com/sv-de" hrefLang="sv-DE" />
        <link rel="alternate" href="https://stripe.com/th-de" hrefLang="th-DE" />
        <link rel="alternate" href="https://stripe.com/pt-br-de" hrefLang="pt-DE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-de" hrefLang="zh-DE" />
        <link rel="alternate" href="https://stripe.com/de-gi" hrefLang="de-GI" />
        <link rel="alternate" href="https://stripe.com/en-gb-gi" hrefLang="en-GI" />
        <link rel="alternate" href="https://stripe.com/es-419-gi" hrefLang="es-GI" />
        <link rel="alternate" href="https://stripe.com/fr-gi" hrefLang="fr-GI" />
        <link rel="alternate" href="https://stripe.com/id-gi" hrefLang="id-GI" />
        <link rel="alternate" href="https://stripe.com/it-gi" hrefLang="it-GI" />
        <link rel="alternate" href="https://stripe.com/ja-gi" hrefLang="ja-GI" />
        <link rel="alternate" href="https://stripe.com/nl-gi" hrefLang="nl-GI" />
        <link rel="alternate" href="https://stripe.com/sv-gi" hrefLang="sv-GI" />
        <link rel="alternate" href="https://stripe.com/th-gi" hrefLang="th-GI" />
        <link rel="alternate" href="https://stripe.com/pt-br-gi" hrefLang="pt-GI" />
        <link rel="alternate" href="https://stripe.com/zh-cn-gi" hrefLang="zh-GI" />
        <link rel="alternate" href="https://stripe.com/de-gr" hrefLang="de-GR" />
        <link rel="alternate" href="https://stripe.com/en-gb-gr" hrefLang="en-GR" />
        <link rel="alternate" href="https://stripe.com/es-419-gr" hrefLang="es-GR" />
        <link rel="alternate" href="https://stripe.com/fr-gr" hrefLang="fr-GR" />
        <link rel="alternate" href="https://stripe.com/id-gr" hrefLang="id-GR" />
        <link rel="alternate" href="https://stripe.com/it-gr" hrefLang="it-GR" />
        <link rel="alternate" href="https://stripe.com/ja-gr" hrefLang="ja-GR" />
        <link rel="alternate" href="https://stripe.com/nl-gr" hrefLang="nl-GR" />
        <link rel="alternate" href="https://stripe.com/sv-gr" hrefLang="sv-GR" />
        <link rel="alternate" href="https://stripe.com/th-gr" hrefLang="th-GR" />
        <link rel="alternate" href="https://stripe.com/pt-br-gr" hrefLang="pt-GR" />
        <link rel="alternate" href="https://stripe.com/zh-cn-gr" hrefLang="zh-GR" />
        <link rel="alternate" href="https://stripe.com/de-hk" hrefLang="de-HK" />
        <link rel="alternate" href="https://stripe.com/en-gb-hk" hrefLang="en-HK" />
        <link rel="alternate" href="https://stripe.com/es-419-hk" hrefLang="es-HK" />
        <link rel="alternate" href="https://stripe.com/fr-hk" hrefLang="fr-HK" />
        <link rel="alternate" href="https://stripe.com/id-hk" hrefLang="id-HK" />
        <link rel="alternate" href="https://stripe.com/it-hk" hrefLang="it-HK" />
        <link rel="alternate" href="https://stripe.com/ja-hk" hrefLang="ja-HK" />
        <link rel="alternate" href="https://stripe.com/nl-hk" hrefLang="nl-HK" />
        <link rel="alternate" href="https://stripe.com/sv-hk" hrefLang="sv-HK" />
        <link rel="alternate" href="https://stripe.com/th-hk" hrefLang="th-HK" />
        <link rel="alternate" href="https://stripe.com/pt-br-hk" hrefLang="pt-HK" />
        <link rel="alternate" href="https://stripe.com/zh-cn-hk" hrefLang="zh-HK" />
        <link rel="alternate" href="https://stripe.com/de-hu" hrefLang="de-HU" />
        <link rel="alternate" href="https://stripe.com/en-gb-hu" hrefLang="en-HU" />
        <link rel="alternate" href="https://stripe.com/es-419-hu" hrefLang="es-HU" />
        <link rel="alternate" href="https://stripe.com/fr-hu" hrefLang="fr-HU" />
        <link rel="alternate" href="https://stripe.com/id-hu" hrefLang="id-HU" />
        <link rel="alternate" href="https://stripe.com/it-hu" hrefLang="it-HU" />
        <link rel="alternate" href="https://stripe.com/ja-hu" hrefLang="ja-HU" />
        <link rel="alternate" href="https://stripe.com/nl-hu" hrefLang="nl-HU" />
        <link rel="alternate" href="https://stripe.com/sv-hu" hrefLang="sv-HU" />
        <link rel="alternate" href="https://stripe.com/th-hu" hrefLang="th-HU" />
        <link rel="alternate" href="https://stripe.com/pt-br-hu" hrefLang="pt-HU" />
        <link rel="alternate" href="https://stripe.com/zh-cn-hu" hrefLang="zh-HU" />
        <link rel="alternate" href="https://stripe.com/de-in" hrefLang="de-IN" />
        <link rel="alternate" href="https://stripe.com/in" hrefLang="en-IN" />
        <link rel="alternate" href="https://stripe.com/es-419-in" hrefLang="es-IN" />
        <link rel="alternate" href="https://stripe.com/fr-in" hrefLang="fr-IN" />
        <link rel="alternate" href="https://stripe.com/id-in" hrefLang="id-IN" />
        <link rel="alternate" href="https://stripe.com/it-in" hrefLang="it-IN" />
        <link rel="alternate" href="https://stripe.com/ja-in" hrefLang="ja-IN" />
        <link rel="alternate" href="https://stripe.com/nl-in" hrefLang="nl-IN" />
        <link rel="alternate" href="https://stripe.com/sv-in" hrefLang="sv-IN" />
        <link rel="alternate" href="https://stripe.com/th-in" hrefLang="th-IN" />
        <link rel="alternate" href="https://stripe.com/pt-br-in" hrefLang="pt-IN" />
        <link rel="alternate" href="https://stripe.com/zh-cn-in" hrefLang="zh-IN" />
        <link rel="alternate" href="https://stripe.com/de-ie" hrefLang="de-IE" />
        <link rel="alternate" href="https://stripe.com/ie" hrefLang="en-IE" />
        <link rel="alternate" href="https://stripe.com/es-419-ie" hrefLang="es-IE" />
        <link rel="alternate" href="https://stripe.com/fr-ie" hrefLang="fr-IE" />
        <link rel="alternate" href="https://stripe.com/id-ie" hrefLang="id-IE" />
        <link rel="alternate" href="https://stripe.com/it-ie" hrefLang="it-IE" />
        <link rel="alternate" href="https://stripe.com/ja-ie" hrefLang="ja-IE" />
        <link rel="alternate" href="https://stripe.com/nl-ie" hrefLang="nl-IE" />
        <link rel="alternate" href="https://stripe.com/sv-ie" hrefLang="sv-IE" />
        <link rel="alternate" href="https://stripe.com/th-ie" hrefLang="th-IE" />
        <link rel="alternate" href="https://stripe.com/pt-br-ie" hrefLang="pt-IE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ie" hrefLang="zh-IE" />
        <link rel="alternate" href="https://stripe.com/de-it" hrefLang="de-IT" />
        <link rel="alternate" href="https://stripe.com/en-gb-it" hrefLang="en-IT" />
        <link rel="alternate" href="https://stripe.com/es-419-it" hrefLang="es-IT" />
        <link rel="alternate" href="https://stripe.com/fr-it" hrefLang="fr-IT" />
        <link rel="alternate" href="https://stripe.com/id-it" hrefLang="id-IT" />
        <link rel="alternate" href="https://stripe.com/it" hrefLang="it-IT" />
        <link rel="alternate" href="https://stripe.com/ja-it" hrefLang="ja-IT" />
        <link rel="alternate" href="https://stripe.com/nl-it" hrefLang="nl-IT" />
        <link rel="alternate" href="https://stripe.com/sv-it" hrefLang="sv-IT" />
        <link rel="alternate" href="https://stripe.com/th-it" hrefLang="th-IT" />
        <link rel="alternate" href="https://stripe.com/pt-br-it" hrefLang="pt-IT" />
        <link rel="alternate" href="https://stripe.com/zh-cn-it" hrefLang="zh-IT" />
        <link rel="alternate" href="https://stripe.com/de-jp" hrefLang="de-JP" />
        <link rel="alternate" href="https://stripe.com/en-jp" hrefLang="en-JP" />
        <link rel="alternate" href="https://stripe.com/es-419-jp" hrefLang="es-JP" />
        <link rel="alternate" href="https://stripe.com/fr-jp" hrefLang="fr-JP" />
        <link rel="alternate" href="https://stripe.com/id-jp" hrefLang="id-JP" />
        <link rel="alternate" href="https://stripe.com/it-jp" hrefLang="it-JP" />
        <link rel="alternate" href="https://stripe.com/jp" hrefLang="ja-JP" />
        <link rel="alternate" href="https://stripe.com/nl-jp" hrefLang="nl-JP" />
        <link rel="alternate" href="https://stripe.com/sv-jp" hrefLang="sv-JP" />
        <link rel="alternate" href="https://stripe.com/th-jp" hrefLang="th-JP" />
        <link rel="alternate" href="https://stripe.com/pt-br-jp" hrefLang="pt-JP" />
        <link rel="alternate" href="https://stripe.com/zh-cn-jp" hrefLang="zh-JP" />
        <link rel="alternate" href="https://stripe.com/de-lv" hrefLang="de-LV" />
        <link rel="alternate" href="https://stripe.com/en-gb-lv" hrefLang="en-LV" />
        <link rel="alternate" href="https://stripe.com/es-419-lv" hrefLang="es-LV" />
        <link rel="alternate" href="https://stripe.com/fr-lv" hrefLang="fr-LV" />
        <link rel="alternate" href="https://stripe.com/id-lv" hrefLang="id-LV" />
        <link rel="alternate" href="https://stripe.com/it-lv" hrefLang="it-LV" />
        <link rel="alternate" href="https://stripe.com/ja-lv" hrefLang="ja-LV" />
        <link rel="alternate" href="https://stripe.com/nl-lv" hrefLang="nl-LV" />
        <link rel="alternate" href="https://stripe.com/sv-lv" hrefLang="sv-LV" />
        <link rel="alternate" href="https://stripe.com/th-lv" hrefLang="th-LV" />
        <link rel="alternate" href="https://stripe.com/pt-br-lv" hrefLang="pt-LV" />
        <link rel="alternate" href="https://stripe.com/zh-cn-lv" hrefLang="zh-LV" />
        <link rel="alternate" href="https://stripe.com/de-li" hrefLang="de-LI" />
        <link rel="alternate" href="https://stripe.com/en-gb-li" hrefLang="en-LI" />
        <link rel="alternate" href="https://stripe.com/es-419-li" hrefLang="es-LI" />
        <link rel="alternate" href="https://stripe.com/fr-li" hrefLang="fr-LI" />
        <link rel="alternate" href="https://stripe.com/id-li" hrefLang="id-LI" />
        <link rel="alternate" href="https://stripe.com/it-li" hrefLang="it-LI" />
        <link rel="alternate" href="https://stripe.com/ja-li" hrefLang="ja-LI" />
        <link rel="alternate" href="https://stripe.com/nl-li" hrefLang="nl-LI" />
        <link rel="alternate" href="https://stripe.com/sv-li" hrefLang="sv-LI" />
        <link rel="alternate" href="https://stripe.com/th-li" hrefLang="th-LI" />
        <link rel="alternate" href="https://stripe.com/pt-br-li" hrefLang="pt-LI" />
        <link rel="alternate" href="https://stripe.com/zh-cn-li" hrefLang="zh-LI" />
        <link rel="alternate" href="https://stripe.com/de-lt" hrefLang="de-LT" />
        <link rel="alternate" href="https://stripe.com/en-gb-lt" hrefLang="en-LT" />
        <link rel="alternate" href="https://stripe.com/es-419-lt" hrefLang="es-LT" />
        <link rel="alternate" href="https://stripe.com/fr-lt" hrefLang="fr-LT" />
        <link rel="alternate" href="https://stripe.com/id-lt" hrefLang="id-LT" />
        <link rel="alternate" href="https://stripe.com/it-lt" hrefLang="it-LT" />
        <link rel="alternate" href="https://stripe.com/ja-lt" hrefLang="ja-LT" />
        <link rel="alternate" href="https://stripe.com/nl-lt" hrefLang="nl-LT" />
        <link rel="alternate" href="https://stripe.com/sv-lt" hrefLang="sv-LT" />
        <link rel="alternate" href="https://stripe.com/th-lt" hrefLang="th-LT" />
        <link rel="alternate" href="https://stripe.com/pt-br-lt" hrefLang="pt-LT" />
        <link rel="alternate" href="https://stripe.com/zh-cn-lt" hrefLang="zh-LT" />
        <link rel="alternate" href="https://stripe.com/de-lu" hrefLang="de-LU" />
        <link rel="alternate" href="https://stripe.com/en-gb-lu" hrefLang="en-LU" />
        <link rel="alternate" href="https://stripe.com/es-419-lu" hrefLang="es-LU" />
        <link rel="alternate" href="https://stripe.com/fr-lu" hrefLang="fr-LU" />
        <link rel="alternate" href="https://stripe.com/id-lu" hrefLang="id-LU" />
        <link rel="alternate" href="https://stripe.com/it-lu" hrefLang="it-LU" />
        <link rel="alternate" href="https://stripe.com/ja-lu" hrefLang="ja-LU" />
        <link rel="alternate" href="https://stripe.com/nl-lu" hrefLang="nl-LU" />
        <link rel="alternate" href="https://stripe.com/sv-lu" hrefLang="sv-LU" />
        <link rel="alternate" href="https://stripe.com/th-lu" hrefLang="th-LU" />
        <link rel="alternate" href="https://stripe.com/pt-br-lu" hrefLang="pt-LU" />
        <link rel="alternate" href="https://stripe.com/zh-cn-lu" hrefLang="zh-LU" />
        <link rel="alternate" href="https://stripe.com/de-my" hrefLang="de-MY" />
        <link rel="alternate" href="https://stripe.com/en-gb-my" hrefLang="en-MY" />
        <link rel="alternate" href="https://stripe.com/es-419-my" hrefLang="es-MY" />
        <link rel="alternate" href="https://stripe.com/fr-my" hrefLang="fr-MY" />
        <link rel="alternate" href="https://stripe.com/id-my" hrefLang="id-MY" />
        <link rel="alternate" href="https://stripe.com/it-my" hrefLang="it-MY" />
        <link rel="alternate" href="https://stripe.com/ja-my" hrefLang="ja-MY" />
        <link rel="alternate" href="https://stripe.com/nl-my" hrefLang="nl-MY" />
        <link rel="alternate" href="https://stripe.com/sv-my" hrefLang="sv-MY" />
        <link rel="alternate" href="https://stripe.com/th-my" hrefLang="th-MY" />
        <link rel="alternate" href="https://stripe.com/pt-br-my" hrefLang="pt-MY" />
        <link rel="alternate" href="https://stripe.com/zh-cn-my" hrefLang="zh-MY" />
        <link rel="alternate" href="https://stripe.com/de-mt" hrefLang="de-MT" />
        <link rel="alternate" href="https://stripe.com/en-gb-mt" hrefLang="en-MT" />
        <link rel="alternate" href="https://stripe.com/es-419-mt" hrefLang="es-MT" />
        <link rel="alternate" href="https://stripe.com/fr-mt" hrefLang="fr-MT" />
        <link rel="alternate" href="https://stripe.com/id-mt" hrefLang="id-MT" />
        <link rel="alternate" href="https://stripe.com/it-mt" hrefLang="it-MT" />
        <link rel="alternate" href="https://stripe.com/ja-mt" hrefLang="ja-MT" />
        <link rel="alternate" href="https://stripe.com/nl-mt" hrefLang="nl-MT" />
        <link rel="alternate" href="https://stripe.com/sv-mt" hrefLang="sv-MT" />
        <link rel="alternate" href="https://stripe.com/th-mt" hrefLang="th-MT" />
        <link rel="alternate" href="https://stripe.com/pt-br-mt" hrefLang="pt-MT" />
        <link rel="alternate" href="https://stripe.com/zh-cn-mt" hrefLang="zh-MT" />
        <link rel="alternate" href="https://stripe.com/de-mx" hrefLang="de-MX" />
        <link rel="alternate" href="https://stripe.com/en-mx" hrefLang="en-MX" />
        <link rel="alternate" href="https://stripe.com/mx" hrefLang="es-MX" />
        <link rel="alternate" href="https://stripe.com/fr-mx" hrefLang="fr-MX" />
        <link rel="alternate" href="https://stripe.com/id-mx" hrefLang="id-MX" />
        <link rel="alternate" href="https://stripe.com/it-mx" hrefLang="it-MX" />
        <link rel="alternate" href="https://stripe.com/ja-mx" hrefLang="ja-MX" />
        <link rel="alternate" href="https://stripe.com/nl-mx" hrefLang="nl-MX" />
        <link rel="alternate" href="https://stripe.com/sv-mx" hrefLang="sv-MX" />
        <link rel="alternate" href="https://stripe.com/th-mx" hrefLang="th-MX" />
        <link rel="alternate" href="https://stripe.com/pt-br-mx" hrefLang="pt-MX" />
        <link rel="alternate" href="https://stripe.com/zh-cn-mx" hrefLang="zh-MX" />
        <link rel="alternate" href="https://stripe.com/de-nl" hrefLang="de-NL" />
        <link rel="alternate" href="https://stripe.com/en-gb-nl" hrefLang="en-NL" />
        <link rel="alternate" href="https://stripe.com/es-419-nl" hrefLang="es-NL" />
        <link rel="alternate" href="https://stripe.com/fr-nl" hrefLang="fr-NL" />
        <link rel="alternate" href="https://stripe.com/id-nl" hrefLang="id-NL" />
        <link rel="alternate" href="https://stripe.com/it-nl" hrefLang="it-NL" />
        <link rel="alternate" href="https://stripe.com/ja-nl" hrefLang="ja-NL" />
        <link rel="alternate" href="https://stripe.com/nl" hrefLang="nl-NL" />
        <link rel="alternate" href="https://stripe.com/sv-nl" hrefLang="sv-NL" />
        <link rel="alternate" href="https://stripe.com/th-nl" hrefLang="th-NL" />
        <link rel="alternate" href="https://stripe.com/pt-br-nl" hrefLang="pt-NL" />
        <link rel="alternate" href="https://stripe.com/zh-cn-nl" hrefLang="zh-NL" />
        <link rel="alternate" href="https://stripe.com/de-nz" hrefLang="de-NZ" />
        <link rel="alternate" href="https://stripe.com/nz" hrefLang="en-NZ" />
        <link rel="alternate" href="https://stripe.com/es-419-nz" hrefLang="es-NZ" />
        <link rel="alternate" href="https://stripe.com/fr-nz" hrefLang="fr-NZ" />
        <link rel="alternate" href="https://stripe.com/id-nz" hrefLang="id-NZ" />
        <link rel="alternate" href="https://stripe.com/it-nz" hrefLang="it-NZ" />
        <link rel="alternate" href="https://stripe.com/ja-nz" hrefLang="ja-NZ" />
        <link rel="alternate" href="https://stripe.com/nl-nz" hrefLang="nl-NZ" />
        <link rel="alternate" href="https://stripe.com/sv-nz" hrefLang="sv-NZ" />
        <link rel="alternate" href="https://stripe.com/th-nz" hrefLang="th-NZ" />
        <link rel="alternate" href="https://stripe.com/pt-br-nz" hrefLang="pt-NZ" />
        <link rel="alternate" href="https://stripe.com/zh-cn-nz" hrefLang="zh-NZ" />
        <link rel="alternate" href="https://stripe.com/de-no" hrefLang="de-NO" />
        <link rel="alternate" href="https://stripe.com/en-gb-no" hrefLang="en-NO" />
        <link rel="alternate" href="https://stripe.com/es-419-no" hrefLang="es-NO" />
        <link rel="alternate" href="https://stripe.com/fr-no" hrefLang="fr-NO" />
        <link rel="alternate" href="https://stripe.com/id-no" hrefLang="id-NO" />
        <link rel="alternate" href="https://stripe.com/it-no" hrefLang="it-NO" />
        <link rel="alternate" href="https://stripe.com/ja-no" hrefLang="ja-NO" />
        <link rel="alternate" href="https://stripe.com/nl-no" hrefLang="nl-NO" />
        <link rel="alternate" href="https://stripe.com/sv-no" hrefLang="sv-NO" />
        <link rel="alternate" href="https://stripe.com/th-no" hrefLang="th-NO" />
        <link rel="alternate" href="https://stripe.com/pt-br-no" hrefLang="pt-NO" />
        <link rel="alternate" href="https://stripe.com/zh-cn-no" hrefLang="zh-NO" />
        <link rel="alternate" href="https://stripe.com/de-pl" hrefLang="de-PL" />
        <link rel="alternate" href="https://stripe.com/en-gb-pl" hrefLang="en-PL" />
        <link rel="alternate" href="https://stripe.com/es-419-pl" hrefLang="es-PL" />
        <link rel="alternate" href="https://stripe.com/fr-pl" hrefLang="fr-PL" />
        <link rel="alternate" href="https://stripe.com/id-pl" hrefLang="id-PL" />
        <link rel="alternate" href="https://stripe.com/it-pl" hrefLang="it-PL" />
        <link rel="alternate" href="https://stripe.com/ja-pl" hrefLang="ja-PL" />
        <link rel="alternate" href="https://stripe.com/nl-pl" hrefLang="nl-PL" />
        <link rel="alternate" href="https://stripe.com/sv-pl" hrefLang="sv-PL" />
        <link rel="alternate" href="https://stripe.com/th-pl" hrefLang="th-PL" />
        <link rel="alternate" href="https://stripe.com/pt-br-pl" hrefLang="pt-PL" />
        <link rel="alternate" href="https://stripe.com/zh-cn-pl" hrefLang="zh-PL" />
        <link rel="alternate" href="https://stripe.com/de-pt" hrefLang="de-PT" />
        <link rel="alternate" href="https://stripe.com/en-gb-pt" hrefLang="en-PT" />
        <link rel="alternate" href="https://stripe.com/es-419-pt" hrefLang="es-PT" />
        <link rel="alternate" href="https://stripe.com/fr-pt" hrefLang="fr-PT" />
        <link rel="alternate" href="https://stripe.com/id-pt" hrefLang="id-PT" />
        <link rel="alternate" href="https://stripe.com/it-pt" hrefLang="it-PT" />
        <link rel="alternate" href="https://stripe.com/ja-pt" hrefLang="ja-PT" />
        <link rel="alternate" href="https://stripe.com/nl-pt" hrefLang="nl-PT" />
        <link rel="alternate" href="https://stripe.com/sv-pt" hrefLang="sv-PT" />
        <link rel="alternate" href="https://stripe.com/th-pt" hrefLang="th-PT" />
        <link rel="alternate" href="https://stripe.com/pt-br-pt" hrefLang="pt-PT" />
        <link rel="alternate" href="https://stripe.com/zh-cn-pt" hrefLang="zh-PT" />
        <link rel="alternate" href="https://stripe.com/de-ro" hrefLang="de-RO" />
        <link rel="alternate" href="https://stripe.com/en-gb-ro" hrefLang="en-RO" />
        <link rel="alternate" href="https://stripe.com/es-419-ro" hrefLang="es-RO" />
        <link rel="alternate" href="https://stripe.com/fr-ro" hrefLang="fr-RO" />
        <link rel="alternate" href="https://stripe.com/id-ro" hrefLang="id-RO" />
        <link rel="alternate" href="https://stripe.com/it-ro" hrefLang="it-RO" />
        <link rel="alternate" href="https://stripe.com/ja-ro" hrefLang="ja-RO" />
        <link rel="alternate" href="https://stripe.com/nl-ro" hrefLang="nl-RO" />
        <link rel="alternate" href="https://stripe.com/sv-ro" hrefLang="sv-RO" />
        <link rel="alternate" href="https://stripe.com/th-ro" hrefLang="th-RO" />
        <link rel="alternate" href="https://stripe.com/pt-br-ro" hrefLang="pt-RO" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ro" hrefLang="zh-RO" />
        <link rel="alternate" href="https://stripe.com/de-sg" hrefLang="de-SG" />
        <link rel="alternate" href="https://stripe.com/en-gb-sg" hrefLang="en-SG" />
        <link rel="alternate" href="https://stripe.com/es-419-sg" hrefLang="es-SG" />
        <link rel="alternate" href="https://stripe.com/fr-sg" hrefLang="fr-SG" />
        <link rel="alternate" href="https://stripe.com/id-sg" hrefLang="id-SG" />
        <link rel="alternate" href="https://stripe.com/it-sg" hrefLang="it-SG" />
        <link rel="alternate" href="https://stripe.com/ja-sg" hrefLang="ja-SG" />
        <link rel="alternate" href="https://stripe.com/nl-sg" hrefLang="nl-SG" />
        <link rel="alternate" href="https://stripe.com/sv-sg" hrefLang="sv-SG" />
        <link rel="alternate" href="https://stripe.com/th-sg" hrefLang="th-SG" />
        <link rel="alternate" href="https://stripe.com/pt-br-sg" hrefLang="pt-SG" />
        <link rel="alternate" href="https://stripe.com/zh-cn-sg" hrefLang="zh-SG" />
        <link rel="alternate" href="https://stripe.com/de-sk" hrefLang="de-SK" />
        <link rel="alternate" href="https://stripe.com/en-gb-sk" hrefLang="en-SK" />
        <link rel="alternate" href="https://stripe.com/es-419-sk" hrefLang="es-SK" />
        <link rel="alternate" href="https://stripe.com/fr-sk" hrefLang="fr-SK" />
        <link rel="alternate" href="https://stripe.com/id-sk" hrefLang="id-SK" />
        <link rel="alternate" href="https://stripe.com/it-sk" hrefLang="it-SK" />
        <link rel="alternate" href="https://stripe.com/ja-sk" hrefLang="ja-SK" />
        <link rel="alternate" href="https://stripe.com/nl-sk" hrefLang="nl-SK" />
        <link rel="alternate" href="https://stripe.com/sv-sk" hrefLang="sv-SK" />
        <link rel="alternate" href="https://stripe.com/th-sk" hrefLang="th-SK" />
        <link rel="alternate" href="https://stripe.com/pt-br-sk" hrefLang="pt-SK" />
        <link rel="alternate" href="https://stripe.com/zh-cn-sk" hrefLang="zh-SK" />
        <link rel="alternate" href="https://stripe.com/de-si" hrefLang="de-SI" />
        <link rel="alternate" href="https://stripe.com/en-gb-si" hrefLang="en-SI" />
        <link rel="alternate" href="https://stripe.com/es-419-si" hrefLang="es-SI" />
        <link rel="alternate" href="https://stripe.com/fr-si" hrefLang="fr-SI" />
        <link rel="alternate" href="https://stripe.com/id-si" hrefLang="id-SI" />
        <link rel="alternate" href="https://stripe.com/it-si" hrefLang="it-SI" />
        <link rel="alternate" href="https://stripe.com/ja-si" hrefLang="ja-SI" />
        <link rel="alternate" href="https://stripe.com/nl-si" hrefLang="nl-SI" />
        <link rel="alternate" href="https://stripe.com/sv-si" hrefLang="sv-SI" />
        <link rel="alternate" href="https://stripe.com/th-si" hrefLang="th-SI" />
        <link rel="alternate" href="https://stripe.com/pt-br-si" hrefLang="pt-SI" />
        <link rel="alternate" href="https://stripe.com/zh-cn-si" hrefLang="zh-SI" />
        <link rel="alternate" href="https://stripe.com/de-es" hrefLang="de-ES" />
        <link rel="alternate" href="https://stripe.com/en-gb-es" hrefLang="en-ES" />
        <link rel="alternate" href="https://stripe.com/es" hrefLang="es-ES" />
        <link rel="alternate" href="https://stripe.com/fr-es" hrefLang="fr-ES" />
        <link rel="alternate" href="https://stripe.com/id-es" hrefLang="id-ES" />
        <link rel="alternate" href="https://stripe.com/it-es" hrefLang="it-ES" />
        <link rel="alternate" href="https://stripe.com/ja-es" hrefLang="ja-ES" />
        <link rel="alternate" href="https://stripe.com/nl-es" hrefLang="nl-ES" />
        <link rel="alternate" href="https://stripe.com/sv-es" hrefLang="sv-ES" />
        <link rel="alternate" href="https://stripe.com/th-es" hrefLang="th-ES" />
        <link rel="alternate" href="https://stripe.com/pt-br-es" hrefLang="pt-ES" />
        <link rel="alternate" href="https://stripe.com/zh-cn-es" hrefLang="zh-ES" />
        <link rel="alternate" href="https://stripe.com/de-se" hrefLang="de-SE" />
        <link rel="alternate" href="https://stripe.com/en-gb-se" hrefLang="en-SE" />
        <link rel="alternate" href="https://stripe.com/es-419-se" hrefLang="es-SE" />
        <link rel="alternate" href="https://stripe.com/fr-se" hrefLang="fr-SE" />
        <link rel="alternate" href="https://stripe.com/id-se" hrefLang="id-SE" />
        <link rel="alternate" href="https://stripe.com/it-se" hrefLang="it-SE" />
        <link rel="alternate" href="https://stripe.com/ja-se" hrefLang="ja-SE" />
        <link rel="alternate" href="https://stripe.com/nl-se" hrefLang="nl-SE" />
        <link rel="alternate" href="https://stripe.com/se" hrefLang="sv-SE" />
        <link rel="alternate" href="https://stripe.com/th-se" hrefLang="th-SE" />
        <link rel="alternate" href="https://stripe.com/pt-br-se" hrefLang="pt-SE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-se" hrefLang="zh-SE" />
        <link rel="alternate" href="https://stripe.com/de-ch" hrefLang="de-CH" />
        <link rel="alternate" href="https://stripe.com/en-gb-ch" hrefLang="en-CH" />
        <link rel="alternate" href="https://stripe.com/es-419-ch" hrefLang="es-CH" />
        <link rel="alternate" href="https://stripe.com/fr-ch" hrefLang="fr-CH" />
        <link rel="alternate" href="https://stripe.com/id-ch" hrefLang="id-CH" />
        <link rel="alternate" href="https://stripe.com/it-ch" hrefLang="it-CH" />
        <link rel="alternate" href="https://stripe.com/ja-ch" hrefLang="ja-CH" />
        <link rel="alternate" href="https://stripe.com/nl-ch" hrefLang="nl-CH" />
        <link rel="alternate" href="https://stripe.com/sv-ch" hrefLang="sv-CH" />
        <link rel="alternate" href="https://stripe.com/th-ch" hrefLang="th-CH" />
        <link rel="alternate" href="https://stripe.com/pt-br-ch" hrefLang="pt-CH" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ch" hrefLang="zh-CH" />
        <link rel="alternate" href="https://stripe.com/de-th" hrefLang="de-TH" />
        <link rel="alternate" href="https://stripe.com/en-gb-th" hrefLang="en-TH" />
        <link rel="alternate" href="https://stripe.com/es-419-th" hrefLang="es-TH" />
        <link rel="alternate" href="https://stripe.com/fr-th" hrefLang="fr-TH" />
        <link rel="alternate" href="https://stripe.com/id-th" hrefLang="id-TH" />
        <link rel="alternate" href="https://stripe.com/it-th" hrefLang="it-TH" />
        <link rel="alternate" href="https://stripe.com/ja-th" hrefLang="ja-TH" />
        <link rel="alternate" href="https://stripe.com/nl-th" hrefLang="nl-TH" />
        <link rel="alternate" href="https://stripe.com/sv-th" hrefLang="sv-TH" />
        <link rel="alternate" href="https://stripe.com/th" hrefLang="th-TH" />
        <link rel="alternate" href="https://stripe.com/pt-br-th" hrefLang="pt-TH" />
        <link rel="alternate" href="https://stripe.com/zh-cn-th" hrefLang="zh-TH" />
        <link rel="alternate" href="https://stripe.com/de-ae" hrefLang="de-AE" />
        <link rel="alternate" href="https://stripe.com/en-gb-ae" hrefLang="en-AE" />
        <link rel="alternate" href="https://stripe.com/es-419-ae" hrefLang="es-AE" />
        <link rel="alternate" href="https://stripe.com/fr-ae" hrefLang="fr-AE" />
        <link rel="alternate" href="https://stripe.com/id-ae" hrefLang="id-AE" />
        <link rel="alternate" href="https://stripe.com/it-ae" hrefLang="it-AE" />
        <link rel="alternate" href="https://stripe.com/ja-ae" hrefLang="ja-AE" />
        <link rel="alternate" href="https://stripe.com/nl-ae" hrefLang="nl-AE" />
        <link rel="alternate" href="https://stripe.com/sv-ae" hrefLang="sv-AE" />
        <link rel="alternate" href="https://stripe.com/th-ae" hrefLang="th-AE" />
        <link rel="alternate" href="https://stripe.com/pt-br-ae" hrefLang="pt-AE" />
        <link rel="alternate" href="https://stripe.com/zh-cn-ae" hrefLang="zh-AE" />
        <link rel="alternate" href="https://stripe.com/de-gb" hrefLang="de-GB" />
        <link rel="alternate" href="https://stripe.com/gb" hrefLang="en-GB" />
        <link rel="alternate" href="https://stripe.com/es-419-gb" hrefLang="es-GB" />
        <link rel="alternate" href="https://stripe.com/fr-gb" hrefLang="fr-GB" />
        <link rel="alternate" href="https://stripe.com/id-gb" hrefLang="id-GB" />
        <link rel="alternate" href="https://stripe.com/it-gb" hrefLang="it-GB" />
        <link rel="alternate" href="https://stripe.com/ja-gb" hrefLang="ja-GB" />
        <link rel="alternate" href="https://stripe.com/nl-gb" hrefLang="nl-GB" />
        <link rel="alternate" href="https://stripe.com/sv-gb" hrefLang="sv-GB" />
        <link rel="alternate" href="https://stripe.com/th-gb" hrefLang="th-GB" />
        <link rel="alternate" href="https://stripe.com/pt-br-gb" hrefLang="pt-GB" />
        <link rel="alternate" href="https://stripe.com/zh-cn-gb" hrefLang="zh-GB" />
        <link rel="alternate" href="https://stripe.com/de-us" hrefLang="de-US" />
        <link rel="alternate" href="https://stripe.com/es-419-us" hrefLang="es-US" />
        <link rel="alternate" href="https://stripe.com/fr-us" hrefLang="fr-US" />
        <link rel="alternate" href="https://stripe.com/id-us" hrefLang="id-US" />
        <link rel="alternate" href="https://stripe.com/it-us" hrefLang="it-US" />
        <link rel="alternate" href="https://stripe.com/ja-us" hrefLang="ja-US" />
        <link rel="alternate" href="https://stripe.com/nl-us" hrefLang="nl-US" />
        <link rel="alternate" href="https://stripe.com/sv-us" hrefLang="sv-US" />
        <link rel="alternate" href="https://stripe.com/th-us" hrefLang="th-US" />
        <link rel="alternate" href="https://stripe.com/pt-br-us" hrefLang="pt-US" />
        <link rel="alternate" href="https://stripe.com/zh-cn-us" hrefLang="zh-US" />



        <title>Stripe | Financial Infrastructure for the Internet</title>


        <meta name="format-detection" content="telephone=no" />










        <meta name="facebook-domain-verification" content="zvsnguqc5l0xz3at5o9beubpl46dv8" />
        <meta property="og:title" content="Stripe | Financial Infrastructure for the Internet" />
        <meta property="og:description" content="Stripe powers online and in-person payment processing and financial solutions for businesses of all sizes. Accept payments, send payouts, and automate financial processes with a suite of APIs and no-code tools." />
        <meta property="og:image" name="og:image" content="https://images.ctfassets.net/fzn2n1nzq965/3AGidihOJl4nH9D1vDjM84/9540155d584be52fc54c443b6efa4ae6/homepage.png?q=80" />

        <meta name="og:url" content="https://stripe.com/" />



        <meta name="twitter:site" content="@stripe" />
        <meta name="twitter:image" content="https://images.ctfassets.net/fzn2n1nzq965/3AGidihOJl4nH9D1vDjM84/9540155d584be52fc54c443b6efa4ae6/homepage.png?q=80" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Stripe | Financial Infrastructure for the Internet" />
        <meta name="twitter:description" content="Stripe powers online and in-person payment processing and financial solutions for businesses of all sizes. Accept payments, send payouts, and automate financial processes with a suite of APIs and no-code tools." />




        <meta name="google-site-verification" content="YZ3mpq9xGeE9VLTDkYo5EkDiyHJthA2_OaPVnclHSUA" />


        <meta name="google-site-verification" content="ZgGi2-xDdfnaWxdfjn5AqtUS11jKWqSXAV_EHODFzdE" />



        <meta name="stripe:notification-path"
          data-js-controller="NotificationCenterLoader"
          data-js-notification-path="/notifications"
        />





        <link rel="preconnect" href="https://q.stripe.com" crossOrigin="true" />
        <link rel="dns-prefetch" href="https://q.stripe.com" />
        <link rel="preconnect" href="https://images.ctfassets.net" crossOrigin="true" />
        <link rel="dns-prefetch" href="https://images.ctfassets.net" />
        <link rel="preconnect" href="https://assets.ctfassets.net" crossOrigin="true" />
        <link rel="dns-prefetch" href="https://assets.ctfassets.net" />




        <link rel="preconnect" href="https://b.stripecdn.com" crossOrigin="true" />
        <link rel="dns-prefetch" href="https://b.stripecdn.com" />


        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GradientLegend-f1cabc70fbf82f3e9c05.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Frontdoor-118109a04e95921931d9.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorStickyAnimation-4ea4d6a5e9b414987337.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorSuiteAnimation-683958a93f82ca151ea7.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnection-192c60d5ff4ac27dec4f.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIcon-f22f360dadf72ca61a47.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIconOutline-2c0929473dcd28db2e99.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorSubanimation-b9163916332f2a67d464.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/DomGraphic-5a317684eb2b9d1f76d2.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorPaymentsAnimation-71bdbfda51a40294b593.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIconGrid-f5ddeb3e7d94044a9646.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorPaymentsGraphic-45fe2caceea82c749c40.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Picture-3f0067e6b392244c9bda.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphicImage-ff4d221174ca6cab4402.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphicOutline-cbb29a27650befdb3913.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphic-ab42746a2bb65d850037.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingAnimation-fa25c03988d3d1f36a35.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphic-c9e3aeda05ab14a454b1.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphicLogo-2cee099c6b840fb58d86.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphicTier-4d3b73ee5f599b93aa50.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectAnimation-f4ce77b995975fa55335.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectFlowDiagram-bcf0320e44c152e1ca03.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectFlowDiagramOrderNotification-b0f6b26d4152317d299d.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIssuingAnimation-ba03e22ccfea12d68c6c.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIssuingCard-b80b51aa94acdc8a688e.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorStandaloneAnimation-5aefb3912ae346b5293e.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductListing-3e17d7acee941b127dd1.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/List-d4c6ad06c173a7dca2ed.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CopyTitle-c641e014b3946628bc95.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/RowLayout-9272a8ee72d3dac4a6ef.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Global-f1eeffae1de3242fcca9.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BackgroundGlobe-64953aedea5f231d07b7.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Globe-b2159f87180df559d2e8.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCardBackground-853f685776c80eaa0089.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CaseStudyCard-60f3f5412530e6e993e8.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCardOverlay-09e527d11b6471566771.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/EnterpriseCarouselAside-b05102a0b81de0c11406.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeProductUsed-448c2bc0913c408517f4.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeProductUsedList-4a8c16b5e5f3fa51247d.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavItem-fd5a8f8fac232f661b35.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavGroup-41fa77c08914b1b778bf.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavTrack-1380f9c2e275695c5ebb.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Track-2f2fce741fc3d8fc8450.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarousel-6ad3f0dce85838a77d8b.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StartUp-3ebb94fdaa25d9c5cfc2.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeSet-a693c0bb21b92fe95891.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Stripe-b3679504f08482f96a0d.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AtlasDashboardGraphic-042f01c5c5f7a5d7ca1a.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductBadge-aa2497ab8abdcc6a3d34.css" media="print" data-js-lazy-style />



        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductFeatureCard-b8fc2abd657c98fece93.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CheckoutFormGraphic-b2509d821651cbc82709.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldInput-3d704dfad5ff81d0e80b.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormField-33f78921d62dc714d424.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CardField-739e285edeecea986ed0.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldInputGrid-281fa6a92c2e3caa14c9.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Field-ea906aa31d4012757deb.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldList-5317148749a9268ec04d.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Form-401d42df82b6e8482f06.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicForm-134bd4e9efb2e0b3a8aa.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksGraphic-753863ac92f9f068a566.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksReceiptGraphic-68e48fc32d105e52ee0c.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksPowdurGraphic-9983a18fe02dbcdc092e.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/HostedInvoiceGraphic-a589a3c1432aa6eb8d38.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/DevelopersCodeEditor-eadbd8bbcdedd8edbbe3.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditor-6eacb8e42c7465ddd557.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorLineNumbers-0eded1c84476ec649145.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorAsciiLoader-c1a350cb85f7a989f599.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorCursor-517911b19e66c94dafbb.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorAutocomplete-dc62d89d9e2121e48baf.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeSyntax-e0768ef33503219c518d.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorStatusBar-24c7c84123b2b6e4f091.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AnimatedCodeEditor-86776e0635434fc49715.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeTerminal-ca23848effb056969042.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/HorizontalOverflowContainer-0b85e8f46a0db21a6ef9.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Icon-646136cd9e336d8c18d7.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AnimatedIcon-0b7478e1f9234aae8838.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LowCodeNoCode-de32a3423ce25c839d82.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BrandModalGraphic-e9e1fc8f4c2bf8a9bd44.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BrandModal-77aed9e8900fc44f1554.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GridLayout-0b90e779a89c0243e739.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/SiteFooterSection-1c0a8e1d30b69be4ef69.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CountryPicker-69008988c83026bda6cd.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Flag-4eba62f8d934073c9e2c.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LocaleControl-09ce62c550a15bb456e5.css" media="print" data-js-lazy-style />
        <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LanguagePicker-65f801973c66428d8dec.css" media="print" data-js-lazy-style />


        <noscript>
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GradientLegend-f1cabc70fbf82f3e9c05.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Frontdoor-118109a04e95921931d9.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorStickyAnimation-4ea4d6a5e9b414987337.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorSuiteAnimation-683958a93f82ca151ea7.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnection-192c60d5ff4ac27dec4f.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIcon-f22f360dadf72ca61a47.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIconOutline-2c0929473dcd28db2e99.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorSubanimation-b9163916332f2a67d464.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/DomGraphic-5a317684eb2b9d1f76d2.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorPaymentsAnimation-71bdbfda51a40294b593.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIconGrid-f5ddeb3e7d94044a9646.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorPaymentsGraphic-45fe2caceea82c749c40.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Picture-3f0067e6b392244c9bda.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphicImage-ff4d221174ca6cab4402.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphicOutline-cbb29a27650befdb3913.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorGraphic-ab42746a2bb65d850037.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingAnimation-fa25c03988d3d1f36a35.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphic-c9e3aeda05ab14a454b1.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphicLogo-2cee099c6b840fb58d86.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorBillingGraphicTier-4d3b73ee5f599b93aa50.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectAnimation-f4ce77b995975fa55335.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectFlowDiagram-bcf0320e44c152e1ca03.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorConnectFlowDiagramOrderNotification-b0f6b26d4152317d299d.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIssuingAnimation-ba03e22ccfea12d68c6c.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorIssuingCard-b80b51aa94acdc8a688e.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/FrontdoorStandaloneAnimation-5aefb3912ae346b5293e.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductListing-3e17d7acee941b127dd1.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/List-d4c6ad06c173a7dca2ed.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CopyTitle-c641e014b3946628bc95.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/RowLayout-9272a8ee72d3dac4a6ef.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Global-f1eeffae1de3242fcca9.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BackgroundGlobe-64953aedea5f231d07b7.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Globe-b2159f87180df559d2e8.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCardBackground-853f685776c80eaa0089.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CaseStudyCard-60f3f5412530e6e993e8.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCardOverlay-09e527d11b6471566771.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/EnterpriseCarouselAside-b05102a0b81de0c11406.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeProductUsed-448c2bc0913c408517f4.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeProductUsedList-4a8c16b5e5f3fa51247d.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavItem-fd5a8f8fac232f661b35.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavGroup-41fa77c08914b1b778bf.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarouselNavTrack-1380f9c2e275695c5ebb.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Track-2f2fce741fc3d8fc8450.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CustomersCaseStudyCarousel-6ad3f0dce85838a77d8b.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StartUp-3ebb94fdaa25d9c5cfc2.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/StripeSet-a693c0bb21b92fe95891.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Stripe-b3679504f08482f96a0d.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AtlasDashboardGraphic-042f01c5c5f7a5d7ca1a.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductBadge-aa2497ab8abdcc6a3d34.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/ProductFeatureCard-b8fc2abd657c98fece93.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CheckoutFormGraphic-b2509d821651cbc82709.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldInput-3d704dfad5ff81d0e80b.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormField-33f78921d62dc714d424.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CardField-739e285edeecea986ed0.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldInputGrid-281fa6a92c2e3caa14c9.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Field-ea906aa31d4012757deb.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicFormFieldList-5317148749a9268ec04d.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Form-401d42df82b6e8482f06.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GraphicForm-134bd4e9efb2e0b3a8aa.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksGraphic-753863ac92f9f068a566.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksReceiptGraphic-68e48fc32d105e52ee0c.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/PaymentLinksPowdurGraphic-9983a18fe02dbcdc092e.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/HostedInvoiceGraphic-a589a3c1432aa6eb8d38.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/DevelopersCodeEditor-eadbd8bbcdedd8edbbe3.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditor-6eacb8e42c7465ddd557.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorLineNumbers-0eded1c84476ec649145.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorAsciiLoader-c1a350cb85f7a989f599.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorCursor-517911b19e66c94dafbb.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorAutocomplete-dc62d89d9e2121e48baf.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeSyntax-e0768ef33503219c518d.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeEditorStatusBar-24c7c84123b2b6e4f091.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AnimatedCodeEditor-86776e0635434fc49715.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CodeTerminal-ca23848effb056969042.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/HorizontalOverflowContainer-0b85e8f46a0db21a6ef9.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Icon-646136cd9e336d8c18d7.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/AnimatedIcon-0b7478e1f9234aae8838.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LowCodeNoCode-de32a3423ce25c839d82.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BrandModalGraphic-e9e1fc8f4c2bf8a9bd44.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/BrandModal-77aed9e8900fc44f1554.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/GridLayout-0b90e779a89c0243e739.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/SiteFooterSection-1c0a8e1d30b69be4ef69.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/CountryPicker-69008988c83026bda6cd.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/Flag-4eba62f8d934073c9e2c.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LocaleControl-09ce62c550a15bb456e5.css" />
          <link rel="stylesheet" href="https://b.stripecdn.com/mkt-statics-srv/assets/LanguagePicker-65f801973c66428d8dec.css" />
        </noscript>

        


  <script type="text/javascript" src="https://b.stripecdn.com/mkt-statics-srv/assets/Prelude-Q2U7OZHZ.js" async/>


        {/* <>
          Use the Script component to load your scripts
          <Script type="application/json" strategy="lazyOnload" data-js-script-registry>
            {JSON.stringify(scriptData)}
          </Script>
          
        </> */}
        <Script strategy="lazyOnload" id='fr'>
          {`
          new MutationObserver(e => {
            for (const d of e) {
              if (d.addedNodes) {
                for (const e of d.addedNodes) {
                  if (e instanceof HTMLLinkElement && void 0 !== e.dataset.jsLazyStyle) {
                    e.addEventListener("load", function() {
                      this.media = "all";
                    });
                  }
                }
              }
            }
          }).observe(document.head, { childList: true });

          document.addEventListener("DOMContentLoaded", () => {
            for (const e of document.querySelectorAll("link[data-js-lazy-style]")) {
              if ("all" !== e.media) {
                e.media = "all";
              }
            }
          });
        `}
        </Script>

        <script type="text/javascript" src="https://b.stripecdn.com/mkt-statics-srv/assets/Prelude-Q2U7OZHZ.js" async/>
      </head>
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
